import type { GitConfig, SkillRecord, SourceRecord } from './types.js';

export const DEFAULT_GIT_CONFIG: GitConfig = {
  loggedIn: false,
  userName: '',
  email: '',
  defaultGitUrl: 'git@git.company.com:ai/clawhub-skills.git',
  defaultBranch: 'main',
  skillsDirectory: 'skills/',
  publishStrategy: 'pull_request',
  authType: 'none',
  lastTestStatus: 'untested',
};

export const DEFAULT_SOURCES: SourceRecord[] = [
  {
    name: 'anthropics-skills',
    url: 'https://github.com/anthropics/skills.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/skills.git',
      enabled: true,
    },
    label: 'Anthropic 官方技能库',
    description: 'Claude 官方技能合集，适合作为基础技能来源。',
    enabled: true,
    default: true,
    builtin: true,
  },
  {
    name: 'superpowers',
    url: 'https://github.com/obra/superpowers.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/superpowers.git',
      enabled: true,
    },
    label: 'Superpowers 工程技能库',
    description: '面向复杂开发、TDD、调试和重构的工程技能库。',
    enabled: true,
    default: false,
    builtin: true,
  },
  {
    name: 'vercel-agent-skills',
    url: 'https://github.com/vercel-labs/agent-skills.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/agent-skills.git',
      enabled: true,
    },
    label: 'Vercel Agent 技能库',
    description: '聚焦 Web、全栈、Next.js 和部署场景的技能库。',
    enabled: true,
    default: false,
    builtin: true,
  },
  {
    name: 'huggingface-skills',
    url: 'https://github.com/huggingface/skills.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/huggingface-skills.git',
      enabled: true,
    },
    label: 'Hugging Face 技能库',
    description: '面向 Hugging Face 与开源模型生态的技能库。',
    enabled: true,
    default: false,
    builtin: true,
  },
  {
    name: 'antigravity-awesome-skills',
    url: 'https://github.com/sickn33/antigravity-awesome-skills.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/antigravity-awesome-skills.git',
      enabled: true,
    },
    label: 'Antigravity 技能合集',
    description: '跨平台 AI 技能资源合集。',
    enabled: true,
    default: false,
    builtin: true,
  },
  {
    name: 'awesome-claude-skills',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/awesome-claude-skills.git',
      enabled: true,
    },
    label: 'Claude 技能资源索引',
    description: 'Claude 技能资源的精选索引，适合发现更多来源。',
    enabled: true,
    default: false,
    builtin: true,
  },
];

export const DEFAULT_SKILLS: SkillRecord[] = [];
