import type { GitConfig, SkillRecord, SourceRecord } from './types.js';

export const DEFAULT_GIT_CONFIG: GitConfig = {
  loggedIn: false,
  userName: '',
  email: '',
  defaultGitUrl: 'git@git.company.com:ai/clawhub-skills.git',
  defaultBranch: 'main',
  skillsDirectory: 'skills/',
  publishStrategy: 'pull_request',
  authType: 'none',
  lastTestStatus: 'untested',
};

export const DEFAULT_SOURCES: SourceRecord[] = [
  {
    name: 'default',
    url: 'https://gitee.com/digital-construction-center_1/suit-skills-lib.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    label: 'Suit Skills 默认源',
    description: '默认技能库，新安装默认启用。',
    enabled: true,
    default: true,
    builtin: true,
  },
  {
    name: 'anthropics-skills',
    url: 'https://github.com/anthropics/skills.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/skills.git',
      enabled: true,
    },
    label: 'Anthropic 官方技能库',
    description: 'Claude 官方技能合集，适合作为基础技能来源。',
    enabled: false,
    default: false,
    builtin: true,
  },
  {
    name: 'superpowers',
    url: 'https://github.com/obra/superpowers.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/superpowers.git',
      enabled: true,
    },
    label: 'Superpowers 工程技能库',
    description: '面向复杂开发、TDD、调试和重构的工程技能库。',
    enabled: false,
    default: false,
    builtin: true,
  },
  {
    name: 'vercel-agent-skills',
    url: 'https://github.com/vercel-labs/agent-skills.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/agent-skills.git',
      enabled: true,
    },
    label: 'Vercel Agent 技能库',
    description: '聚焦 Web、全栈、Next.js 和部署场景的技能库。',
    enabled: false,
    default: false,
    builtin: true,
  },
  {
    name: 'huggingface-skills',
    url: 'https://github.com/huggingface/skills.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/huggingface-skills.git',
      enabled: true,
    },
    label: 'Hugging Face 技能库',
    description: '面向 Hugging Face 与开源模型生态的技能库。',
    enabled: false,
    default: false,
    builtin: true,
  },
  {
    name: 'antigravity-awesome-skills',
    url: 'https://github.com/sickn33/antigravity-awesome-skills.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/antigravity-awesome-skills.git',
      enabled: true,
    },
    label: 'Antigravity 技能合集',
    description: '跨平台 AI 技能资源合集。',
    enabled: false,
    default: false,
    builtin: true,
  },
  {
    name: 'awesome-claude-skills',
    url: 'https://github.com/ComposioHQ/awesome-claude-skills.git',
    branch: 'main',
    skillsDirectory: 'skills/',
    publishEnabled: false,
    domesticMirror: {
      url: 'https://gitee.com/zhujun12/awesome-claude-skills.git',
      enabled: true,
    },
    label: 'Claude 技能资源索引',
    description: 'Claude 技能资源的精选索引，适合发现更多来源。',
    enabled: false,
    default: false,
    builtin: true,
  },
];

export const DEFAULT_SKILLS: SkillRecord[] = [
  {
    id: 'skill-frontend-design',
    name: 'frontend-design',
    description: 'Create high-quality Web pages, components, and console interfaces for React/Vite projects.',
    author: 'Design Ops',
    source: 'default',
    category: 'frontend',
    version: '2.2.0',
    installs: 12840,
    rating: 4.9,
    reviews: 186,
    status: 'verified',
    tags: ['React', 'UI', 'Dashboard'],
    command: 'npx suit-skills@latest install frontend-design',
    updatedAt: '2026-04-26T01:30:00.000Z',
    owner: 'platform',
    uploadStatus: 'published',
  },
  {
    id: 'skill-java-bugfix',
    name: 'java-bugfix-workflow',
    description: 'Diagnose and repair Java, Spring, MyBatis, startup, API, and SQL issues.',
    author: 'Backend Guild',
    source: 'default',
    category: 'backend',
    version: '1.1.4',
    installs: 7210,
    rating: 4.7,
    reviews: 94,
    status: 'verified',
    tags: ['Java', 'Spring', 'Bugfix'],
    command: 'npx suit-skills@latest install java-bugfix-workflow',
    updatedAt: '2026-04-25T10:12:00.000Z',
    owner: 'platform',
    uploadStatus: 'published',
  },
  {
    id: 'skill-docx',
    name: 'docx',
    description: 'Create, edit, and format Word documents, reports, templates, comments, and structured content.',
    author: 'Document Team',
    source: 'default',
    category: 'document',
    version: '0.8.9',
    installs: 5140,
    rating: 4.6,
    reviews: 61,
    status: 'verified',
    tags: ['Word', 'Report', 'Office'],
    command: 'npx suit-skills@latest install docx',
    updatedAt: '2026-04-24T08:40:00.000Z',
    owner: 'platform',
    uploadStatus: 'published',
  },
  {
    id: 'skill-szj-localize',
    name: 'szj-deps-localize',
    description: 'Move remote-service-dependent SZJ frontend packages into customer local servers.',
    author: 'Delivery Team',
    source: 'default',
    category: 'delivery',
    version: '0.6.1',
    installs: 980,
    rating: 4.2,
    reviews: 28,
    status: 'review',
    tags: ['Migration', 'Private deploy', 'Delivery'],
    command: 'npx suit-skills@latest install szj-deps-localize',
    updatedAt: '2026-04-22T13:11:00.000Z',
    owner: 'delivery',
    uploadStatus: 'waiting_publish',
  },
  {
    id: 'skill-audit',
    name: 'audit',
    description: 'Check accessibility, performance, responsive behavior, theme consistency, and frontend risk.',
    author: 'Quality Lab',
    source: 'default',
    category: 'quality',
    version: '1.5.0',
    installs: 8360,
    rating: 4.8,
    reviews: 112,
    status: 'verified',
    tags: ['Audit', 'A11y', 'Performance'],
    command: 'npx suit-skills@latest install audit',
    updatedAt: '2026-04-20T05:05:00.000Z',
    owner: 'platform',
    uploadStatus: 'published',
  },
  {
    id: 'skill-plugin-creator',
    name: 'plugin-creator',
    description: 'Scaffold Codex plugin directories, plugin.json files, local bundles, and marketplace entries.',
    author: 'Platform Team',
    source: 'default',
    category: 'platform',
    version: '0.3.8',
    installs: 1420,
    rating: 4.4,
    reviews: 35,
    status: 'new',
    tags: ['Plugin', 'Scaffold', 'Codex'],
    command: 'npx suit-skills@latest install plugin-creator',
    updatedAt: '2026-04-18T03:26:00.000Z',
    owner: 'platform',
    uploadStatus: 'published',
  },
];
